{
 "title": "Alert Status",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "panels": [
  { "title": "Active Alert List", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Active Ceph Alert List", "type": "alertlist", "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 } },
  { "title": "Health Checks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Overall Ceph Health",
   "type": "graph",
   "description": "The chart plots the clusters health, over time. Health is depicted as a integer; 0, 1 or 2 where 0 is OK, 1 is WARN and 2 represents an ERROR state.",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ceph_health_status", "legendFormat": "Ceph Health" }
   ]
  },
  {
   "title": "Disks Near Full",
   "type": "graph",
   "description": "This shows how many disks are at or above 80% full. Performance may degrade beyond this threshold on filestore (XFS) backed OSD's.",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count((ceph_osd_stat_bytes_used / ceph_osd_stat_bytes) * 100 > 85)"
    }
   ]
  },
  {
   "title": "OSDs Down",
   "type": "graph",
   "description": "Count of OSDs currently in a DOWN state",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(ceph_osd_metadata) - count(ceph_osd_up > 0.5)",
     "legendFormat": "down"
    }
   ]
  },
  {
   "title": "OSDs Hosts Down",
   "type": "graph",
   "description": "Count of OSD Hosts that have all daemons down",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(\n  (count by(instance) (ceph_disk_occupation * \n    on(ceph_daemon) group_right(instance) ceph_osd_up == 0) - \n  count by(instance) (ceph_disk_occupation)) == 0)",
     "legendFormat": "down"
    }
   ]
  },
  {
   "title": "PG's Stuck",
   "type": "graph",
   "description": "This chart shows whether there are pg's in a stuck state, that need manual intervention to resolve.",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(ceph_osd_numpg) - scalar(ceph_pg_active)",
     "legendFormat": "# pg's stuck inactive"
    }
   ]
  },
  {
   "title": "OSD Host Loss Check",
   "type": "graph",
   "description": "This graph checks the cluster @ 90% full is enough to support the loss of the largest OSD host",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "max(\n  sum(ceph_osd_stat_bytes - ceph_osd_stat_bytes_used)\n) * 0.9 -\nmax(\n  sum by (instance) (\n    ceph_osd_stat_bytes + on (ceph_daemon) group_left (instance) (ceph_disk_occupation*0)\n  )\n)"
    }
   ]
  },
  {
   "title": "Slow OSD responses",
   "type": "graph",
   "description": "Graph checking for OSD Latencies that are above 1s.",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "none", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "(\n  (\n    irate(node_disk_read_time_ms[5m]) / clamp_min(irate(node_disk_reads_completed[5m]), 0.001) +\n    irate(node_disk_write_time_ms[5m]) / clamp_min(irate(node_disk_writes_completed[5m]), 0.001)\n  ) and on (instance, device) ceph_disk_occupation\n) >= 1000",
     "legendFormat": "{{instance}}.{{device}}"
    }
   ]
  },
  {
   "title": "Network Packet Drops/Errors",
   "type": "graph",
   "description": "Checks all interfaces for dropped/error packets, and alerts if more than 10 are seen in a 5m interval",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (instance, device) (\n  irate(node_network_receive_drop{device=~\"(eth|en|bond|ib|mlx).*\"}[5m]) +\n  irate(node_network_receive_errs{device=~\"(eth|en|bond|ib|mlx).*\"}[5m]) +\n  irate(node_network_transmit_drop{device=~\"(eth|en|bond|ib|mlx).*\"}[5m]) +\n  irate(node_network_transmit_errs{device=~\"(eth|en|bond|ib|mlx).*\"}[5m])\n) > 0",
     "legendFormat": "{{instance}} / {{device}}"
    }
   ]
  },
  {
   "title": "Pool Capacity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "ceph_pool_bytes_used / (ceph_pool_bytes_used + ceph_pool_max_avail) * 100 + on (pool_id) group_left (name) (ceph_pool_metadata*0)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "MONs Down",
   "type": "graph",
   "description": "Count of MONs currently not in quorum/down",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(ceph_mon_quorum_status != 1)",
     "legendFormat": "down"
    }
   ]
  },
  {
   "title": "Cluster Capacity",
   "type": "graph",
   "description": "This trigger raises a notification if the raw used crosses the 85% capacity threshold of the ceph cluster",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(ceph_osd_stat_bytes_used) / sum(ceph_osd_stat_bytes) * 100 ",
     "legendFormat": "Raw Capacity Used %"
    }
   ]
  },
  {
   "title": "OSDs with High PG Count",
   "type": "graph",
   "description": "Shows the number of PGs that have a pg count > 275.",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "#NUM OSDs with high PG Count" }
   ],
   "targets": [
    { "expr": "count(ceph_osd_numpg > 275)" }
   ]
  }
 ]
}