{
 "title": "Ceph - At A Glance",
 "tags": [ "overview" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "percentile", "label": "Percentile", "query": "80,85,90,95,98" },
   { "name": "disk_full_threshold", "query": "85" },
   { "name": "growth_window", "query": "7d" },
   {
    "name": "osd_servers",
    "label": "OSD Host",
    "query": "label_values(ceph_disk_occupation, instance)"
   },
   {
    "name": "osd_servers_raw",
    "label": "OSD Host",
    "query": "label_values(ceph_disk_occupation, instance)"
   }
  ]
 },
 "panels": [
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {}
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {}
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {}
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {}
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {}
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {}
   ]
  },
  { "title": "Active Alerts", "type": "alertlist", "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 } },
  { "title": "At a Glance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Health",
   "type": "singlestat",
   "description": "Shows the overall health of the ceph cluster",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ceph_health_status",
     "target": "consolidateBy(maxSeries(collectd.*.$domain.cephmetrics.gauge.$cluster_name.mon.health),\"max\")"
    }
   ]
  },
  {
   "type": "vonage-status-panel",
   "gridPos": { "h": 6, "w": 2, "x": 2, "y": 5 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "total",
     "displayType": "Regular",
     "expr": "count(ceph_mon_quorum_status)",
     "legendFormat": "total",
     "target": "alias(keepLastValue(consolidateBy(maxSeries(collectd.$mon_servers.$domain.cephmetrics.gauge.$cluster_name.mon.num_mon), \"max\")),\"total\")",
     "valueHandler": "Text Only"
    },
    {
     "aggregation": "Last",
     "alias": "quorum",
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "count(ceph_mon_quorum_status == 1)",
     "legendFormat": "quorum",
     "target": "alias(keepLastValue(consolidateBy(maxSeries(collectd.$mon_servers.$domain.cephmetrics.gauge.$cluster_name.mon.num_mon_quorum), \"max\")),\"quorum\")",
     "valueHandler": "String Threshold",
     "warn": "1"
    },
    {
     "aggregation": "Last",
     "alias": "down",
     "crit": 2,
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "count(ceph_mon_quorum_status != 1)",
     "legendFormat": "down",
     "target": "alias(diffSeries(#D,#E), \"down\")",
     "targetFull": "alias(diffSeries(alias(keepLastValue(consolidateBy(maxSeries(collectd.$mon_servers.$domain.cephmetrics.gauge.$cluster_name.mon.num_mon), \"max\")),\"total\"),alias(keepLastValue(consolidateBy(maxSeries(collectd.$mon_servers.$domain.cephmetrics.gauge.$cluster_name.mon.num_mon_quorum), \"max\")),\"quorum\")), \"down\")",
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 1
    }
   ]
  },
  {
   "type": "vonage-status-panel",
   "gridPos": { "h": 6, "w": 2, "x": 4, "y": 5 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "total",
     "displayType": "Regular",
     "expr": "count(ceph_osd_up)",
     "legendFormat": "total",
     "target": "alias(keepLastValue(consolidateBy(maxSeries(collectd.$mon_servers.$domain.cephmetrics.gauge.$cluster_name.mon.num_osd), \"max\")),\"total\")",
     "valueHandler": "Text Only"
    },
    {
     "aggregation": "Last",
     "alias": "in",
     "displayType": "Regular",
     "expr": "count(ceph_osd_up == 1)",
     "legendFormat": "up",
     "target": "alias(keepLastValue(consolidateBy(maxSeries(collectd.$mon_servers.$domain.cephmetrics.gauge.$cluster_name.mon.num_osd_up), \"max\")),\"up\")",
     "valueHandler": "Text Only"
    },
    {
     "aggregation": "Last",
     "alias": "up",
     "displayType": "Regular",
     "expr": "count(ceph_osd_in == 1)",
     "legendFormat": "in",
     "target": "alias(keepLastValue(consolidateBy(maxSeries(collectd.$mon_servers.$domain.cephmetrics.gauge.$cluster_name.mon.num_osd_in), \"max\")),\"in\")",
     "valueHandler": "Text Only"
    },
    {
     "aggregation": "Last",
     "alias": "out",
     "displayType": "Regular",
     "expr": "count(ceph_osd_in == 0)",
     "legendFormat": "out",
     "target": "alias(countSeries(currentBelow(groupByNode(transformNull(collectd.*.$domain.cephmetrics.gauge.$cluster_name.mon.osd_state.*.in,99),-2,\"maxSeries\"),0.5)),\"out\")",
     "valueHandler": "Text Only"
    },
    {
     "aggregation": "Last",
     "alias": "down",
     "crit": 5,
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "count(ceph_osd_up == 0)",
     "legendFormat": "down",
     "target": "alias(countSeries(currentBelow(groupByNode(transformNull(collectd.*.$domain.cephmetrics.gauge.$cluster_name.mon.osd_state.*.up,99),-2,\"maxSeries\"),0.5)),\"down\")",
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 1
    }
   ]
  },
  {
   "type": "vonage-status-panel",
   "gridPos": { "h": 6, "w": 2, "x": 6, "y": 5 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "total",
     "displayType": "Regular",
     "expr": "count(\n  count(\n    ceph_disk_occupation\n  ) by (instance)\n)",
     "legendFormat": "total",
     "target": "alias(countSeries(collectd.*.$domain.cephmetrics.gauge.$cluster_name.osd.num_osds),\"total\")",
     "valueHandler": "Text Only"
    },
    {
     "aggregation": "Last",
     "alias": "up",
     "displayType": "Regular",
     "expr": "count(\n  count(\n    ceph_disk_occupation\n  ) by (instance)) -\ncount(\n  (count by(instance) (ceph_disk_occupation * \n    on(ceph_daemon) group_right(instance) ceph_osd_up == 0) - \n  count by(instance) (ceph_disk_occupation)) == 0)",
     "legendFormat": "up",
     "target": "alias(countSeries(currentAbove(collectd.*.$domain.cephmetrics.gauge.$cluster_name.osd.num_osds,0)),\"up\")",
     "valueHandler": "Text Only"
    },
    {
     "aggregation": "Last",
     "alias": "down",
     "crit": 2,
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "count(\n  (count by(instance) (ceph_disk_occupation * \n    on(ceph_daemon) group_right(instance) ceph_osd_up == 0) - \n  count by(instance) (ceph_disk_occupation)) == 0)",
     "legendFormat": "down",
     "target": "alias(diffSeries(#A, #B), \"down\")",
     "targetFull": "alias(diffSeries(alias(countSeries(collectd.*.$domain.cephmetrics.gauge.$cluster_name.osd.num_osds),\"total\"), alias(countSeries(currentAbove(collectd.*.$domain.cephmetrics.gauge.$cluster_name.osd.num_osds,0)),\"up\")), \"down\")",
     "units": "none",
     "url": "dashboard/db/ceph-health",
     "valueHandler": "Number Threshold",
     "warn": 1
    }
   ]
  },
  {
   "title": "RGWs",
   "type": "singlestat",
   "description": "Number of RGW daemons active",
   "gridPos": { "h": 6, "w": 2, "x": 8, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "count(ceph_rgw_metadata)" }
   ]
  },
  {
   "title": "MDS",
   "type": "singlestat",
   "description": "Number of MDS daemons active",
   "gridPos": { "h": 6, "w": 2, "x": 10, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "count(ceph_mds_metadata)" }
   ]
  },
  {
   "title": "Capacity Utilization",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 5 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ceph_osd_stat_bytes_used) / sum(ceph_osd_stat_bytes) * 100",
     "target": "alias(maxSeries(groupByNode(collectd.*.$domain.cephmetrics.gauge.$cluster_name.mon.osd_bytes, 1,\"maxSeries\")), \"raw capacity\")"
    }
   ]
  },
  {
   "title": "$growth_window Growth Rate",
   "type": "singlestat",
   "description": "Shows the growth rate based on osd usage over the past $growth_window.",
   "gridPos": { "h": 6, "w": 2, "x": 16, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "topk(1, ceph_cluster_total_used_bytes offset 1d) - ignoring (instance,job) topk(1, ceph_cluster_total_used_bytes offset 7d)"
    }
   ]
  },
  {
   "title": "Weeks Remaining",
   "type": "singlestat",
   "description": "Shows the estimated number of weeks left, based on consumption over the past $growth_window.",
   "gridPos": { "h": 6, "w": 2, "x": 18, "y": 5 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "(ceph_cluster_total_bytes - ceph_cluster_total_used_bytes) /\n  scalar(topk(1, ceph_cluster_total_used_bytes offset 1d) - ignoring (instance,job) topk(1, ceph_cluster_total_used_bytes offset 7d))\n",
     "target": "alias(consolidateBy(maxSeries(timeShift(collectd.*.$domain.cephmetrics.gauge.$cluster_name.mon.osd_bytes_used,\"7d\")), \"max\"),\"-$growth_window ago\")"
    }
   ]
  },
  {
   "title": "Placement Group Status",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ceph_pg_active",
     "legendFormat": "Active",
     "target": "alias(keepLastValue(consolidateBy(maxSeries(collectd.$mon_servers.$domain.cephmetrics.gauge.$cluster_name.mon.num_pg_active), \"max\")),\"active\")"
    },
    {
     "expr": "ceph_pg_degraded",
     "legendFormat": "Degraded",
     "target": "alias(diffSeries(#B,#A),\"active + degraded\")",
     "targetFull": "alias(diffSeries(alias(keepLastValue(consolidateBy(maxSeries(collectd.$mon_servers.$domain.cephmetrics.gauge.$cluster_name.mon.num_pg_active), \"max\")),\"active\"),alias(keepLastValue(consolidateBy(maxSeries(collectd.$mon_servers.$domain.cephmetrics.gauge.$cluster_name.mon.num_pg_active_clean), \"max\")),\"active + clean\")),\"active + degraded\")"
    },
    {
     "expr": "ceph_pg_peering",
     "legendFormat": "Peering",
     "target": "alias(consolidateBy(maxSeries(collectd.$mon_servers.$domain.cephmetrics.gauge.$cluster_name.mon.num_pg_peering), \"max\"),\"peering\")"
    },
    { "expr": "ceph_pg_unknown", "legendFormat": "Unknown" }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Recovery/Backfill Ops",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(ceph_osd_recovery_ops[1m]))",
     "target": "sumSeries(groupByNode(collectd.*.$domain.cephmetrics.gauge.$cluster_name.mon.pools.*.recovering_bytes_per_sec,-2,\"avg\"))"
    }
   ]
  },
  {
   "title": "Scrub",
   "type": "singlestat",
   "description": "This panel indicate whether scrub/deep scrub is running within the cluster. NB. If either of these features are turned off, the cluster will enter a WARN state. Click on the panel or the link below to look at cluster information in more detail",
   "gridPos": { "h": 6, "w": 2, "x": 4, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ceph_pg_scrubbing{job=\"ceph\"}",
     "target": "consolidateBy(maxSeries(collectd.*.$domain.cephmetrics.gauge.$cluster_name.mon.features.deep_scrub),\"max\")"
    }
   ]
  },
  {
   "title": "Client IOPS",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\n  rate(ceph_pool_wr[$__interval])\n)\n+ \nsum(\n  rate(ceph_pool_rd[$__interval])\n)",
     "legendFormat": "IOPS",
     "measurement": "collectd.obj-mon-1.storage.lab.cephmetrics.gauge.ceph.mon.pools._all_.read_op_per_sec",
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "target": "sumSeries(groupByNode(collectd.*.$domain.cephmetrics.gauge.$cluster_name.mon.pools.*.op_per_sec,-2,\"maxSeries\"))"
    }
   ]
  },
  {
   "title": "Client Throughput",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 12 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(ceph_pool_wr_bytes[$__interval]) + rate(ceph_pool_rd_bytes[$__interval]))",
     "measurement": "collectd.obj-mon-1.storage.lab.cephmetrics.gauge.ceph.mon.pools._all_.read_op_per_sec",
     "query": "SELECT \"value\" FROM \"collectd.obj-mon-1.storage.lab.cephmetrics.gauge.ceph.mon.pools._all_.read_bytes_sec\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "target": "sumSeries(groupByNode(collectd.*.$domain.cephmetrics.gauge.$cluster_name.mon.pools.*.bytes_sec,-2,\"maxSeries\"))"
    }
   ]
  },
  {
   "title": "Pools",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 14, "y": 12 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ceph_pool_metadata)",
     "measurement": "collectd.obj-mon-1.storage.lab.cephmetrics.gauge.ceph.mon.num_pool",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "target": "maxSeries(collectd.*.$domain.cephmetrics.gauge.$cluster_name.mon.num_pool)"
    }
   ]
  },
  {
   "title": "Client Read/Write Ratio",
   "type": "grafana-piechart-panel",
   "description": "Shows the read/write threshold of client IOPS serviced by the ceph cluster",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "round(sum(irate(ceph_pool_rd[30s])))",
     "legendFormat": "reads",
     "target": "alias(sumSeries(groupByNode(collectd.*.$domain.cephmetrics.gauge.$cluster_name.mon.pools.*.read_op_per_sec,-2,\"maxSeries\")), \"Reads\")"
    },
    {
     "expr": "round(sum(irate(ceph_pool_wr[30s])))",
     "legendFormat": "writes",
     "target": "alias(sumSeries(groupByNode(collectd.*.$domain.cephmetrics.gauge.$cluster_name.mon.pools.*.write_op_per_sec,-2,\"maxSeries\")), \"Writes\")"
    }
   ]
  },
  {
   "title": "OSD Apply vs Commit Latency",
   "type": "graph",
   "description": "Shows the OSD apply and commit latency at the $percentile%ile across the cluster over the past 15 minutes",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "quantile($percentile / 100, ceph_osd_commit_latency_ms)",
     "legendFormat": "commit",
     "target": "alias(percentileOfSeries(collectd.*.$domain.cephmetrics.gauge.$cluster_name.osd.*.apply_latency,$percentile), \"Apply Latency\")"
    },
    {
     "expr": "quantile($percentile / 100, ceph_osd_apply_latency_ms)",
     "legendFormat": "apply",
     "target": "alias(percentileOfSeries(collectd.*.$domain.cephmetrics.gauge.$cluster_name.osd.*.commitcycle_latency, $percentile), \"Commit Latency\")"
    }
   ]
  },
  {
   "title": "OSD Hosts CPU Busy",
   "type": "singlestat",
   "description": "CPU usage is presented based on the $percentile%ile across all OSD hosts",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 18 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "quantile(\n  $percentile / 100, (\n    avg (\n      sum (\n        irate(node_cpu{mode=~\"(system|user|irq|nice)\", instance=~'[[osd_servers_raw]].*'}[1m]))\n      by (instance,cpu)\n    ) by (instance)\n  ) * 100\n)",
     "target": "percentileOfSeries(groupByNode(collectd.$osd_servers.$domain.cpu.percent.{system,user,wait},1,\"sumSeries\"),$percentile)"
    }
   ]
  },
  {
   "title": "RAM Util.",
   "type": "singlestat",
   "description": "RAM Usage shows the $percentile%ile of RAM used across all OSD hosts",
   "gridPos": { "h": 6, "w": 2, "x": 4, "y": 18 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "quantile(\n  $percentile/100, \n  (\n    node_memory_MemTotal{job='node'} - node_memory_MemFree{job='node'} - node_memory_Buffers{job='node'} - node_memory_Cached{job='node'}\n  ) / node_memory_MemTotal{job='node'} * 100\n)",
     "measurement": "collectd.obj-mon-1.storage.lab.cephmetrics.gauge.ceph.mon.pools._all_.read_op_per_sec",
     "query": "SELECT \"value\" FROM \"collectd.obj-mon-1.storage.lab.cephmetrics.gauge.ceph.mon.pools._all_.read_bytes_sec\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "target": "percentileOfSeries(collectd.$osd_servers.$domain.memory.percent.used,$percentile)"
    }
   ]
  },
  {
   "title": "Disk IOPS",
   "type": "singlestat",
   "description": "Total IOPS from all OSDs in the cluster",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\n  sum(\n    rate(\n      node_disk_reads_completed[$__interval]\n    )\n  ) by (instance,device)\n   + ignoring(ceph_daemon,job) group_right(instance) ceph_disk_occupation\n)\n+\nsum(\n  sum(\n    rate(\n      node_disk_writes_completed[$__interval]\n    )\n  ) by (instance,device)\n   + ignoring(ceph_daemon,job) group_right(instance) ceph_disk_occupation\n)",
     "measurement": "collectd.obj-mon-1.storage.lab.cephmetrics.gauge.ceph.mon.pools._all_.read_op_per_sec",
     "query": "SELECT \"value\" FROM \"collectd.obj-mon-1.storage.lab.cephmetrics.gauge.ceph.mon.pools._all_.read_bytes_sec\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "target": "alias(sumSeries(collectd.$osd_servers.$domain.cephmetrics.gauge.$cluster_name.osd.*.perf.iops),\"IOPS\")"
    }
   ]
  },
  {
   "title": "Disk Throughput",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 18 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "# should only include OSD hosts\nsum(\n  sum(\n    rate(\n      node_disk_bytes_read[$__interval]\n    )\n  ) by (instance,device)\n  + ignoring(ceph_daemon,job) group_right(instance) ceph_disk_occupation\n)\n+\nsum(\n  sum(\n    rate(\n      node_disk_bytes_written[$__interval]\n    )\n  ) by (instance,device)\n  + ignoring(ceph_daemon,job) group_right(instance) ceph_disk_occupation\n)",
     "measurement": "collectd.obj-mon-1.storage.lab.cephmetrics.gauge.ceph.mon.pools._all_.read_op_per_sec",
     "query": "SELECT \"value\" FROM \"collectd.obj-mon-1.storage.lab.cephmetrics.gauge.ceph.mon.pools._all_.read_bytes_sec\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "target": "sumSeries(collectd.$osd_servers.$domain.cephmetrics.gauge.$cluster_name.osd.*.perf.bytes_per_sec)"
    }
   ]
  },
  {
   "title": "Nearly Full Disks",
   "type": "singlestat",
   "description": "The count of the number of disks in the cluster that are over $disk_full_threshold% full.",
   "gridPos": { "h": 6, "w": 2, "x": 14, "y": 18 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(\n  (ceph_osd_stat_bytes_used / ceph_osd_stat_bytes) > ($disk_full_threshold / 100)\n)",
     "target": "countSeries(currentAbove(transformNull(keepLastValue(collectd.*.$domain.cephmetrics.gauge.$cluster_name.osd.*.osd_percent_used),0),$disk_full_threshold))"
    }
   ]
  },
  {
   "title": "Disk Latency",
   "type": "singlestat",
   "description": "This panel shows the 5th %ile disk latency, indicating that 95% of the OSDs are delivering this latency or higher",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 18 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "quantile(\n  5 / 100,\n    (irate(node_disk_read_time_ms[1m]) + irate(node_disk_write_time_ms[1m]) / \n    (irate(node_disk_reads_completed[1m]) + irate(node_disk_writes_completed[1m])) \n    +\n    ignoring(ceph_daemon,job) ceph_disk_occupation))"
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "graph",
   "description": "Chart shows the disk utilization over the past 15 mins expressed as an average across all OSDs, and at the $percentile%ile.",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg (\n  max by (device) (\n    irate(node_disk_io_time_ms[1m]) \n    and on (instance, device) ceph_disk_occupation\n  ) / 10\n)",
     "legendFormat": "average",
     "target": "alias(averageSeries(collectd.*.$domain.cephmetrics.gauge.$cluster_name.osd.*.perf.util), 'average %util')"
    },
    {
     "expr": "quantile(\n  $percentile/100, \n  (\n    max by (device) (\n      irate(node_disk_io_time_ms[1m]) \n      and on (instance, device) ceph_disk_occupation\n    ) / 10\n  )\n)",
     "legendFormat": "$percentile%ile",
     "target": "alias(percentileOfSeries(collectd.*.$domain.cephmetrics.gauge.$cluster_name.osd.*.perf.util, $percentile, 'false'), '%util @ $percentile%ile')"
    }
   ]
  }
 ]
}