{
 "title": "Cephmetrics Host Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "panels": [
  { "title": "CPU & RAM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cephmetrics Host CPU Busy %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu{job=\"cephmetrics\",mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "{{Busy %}}"
    }
   ]
  },
  {
   "title": "Cephmetrics Host  CPU Usage Breakdown",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(avg by(mode) (irate(node_cpu{job=\"cephmetrics\",mode!=\"idle\"}[30s]))*100)",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal{job=\"cephmetrics\"} - node_memory_MemAvailable{job=\"cephmetrics\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_MemTotal{job=\"cephmetrics\"} ",
     "legendFormat": "Installed"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Disk Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent", "label": "%UTIL" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_ms{job='cephmetrics',device=~\"[h,s,v]d[a-z]\"}[1m]) / 10",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "none", "label": "IOPS" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed{job=\"cephmetrics\",device=~\"[h,s,v]d[a-z]\"}[30s]) + irate(node_disk_writes_completed{job=~\"cephmetrics\",device=~\"[h,s,v]d[a-z]\"}[30s])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "bytes", "label": "Throughput" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_bytes_read{job='cephmetrics',device=~\"[h,s,v]d[a-z]\"}[1m]) + irate(node_disk_bytes_written{job='cephmetrics',device=~\"[h,s,v]d[a-z]\"}[1m])  ",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "(irate(node_disk_write_time_ms{job='cephmetrics',device=~\"[h,s,v]d[a-z]\"}[1m]) + irate(node_disk_read_time_ms{job='cephmetrics',device=~\"[h,s,v]d[a-z]\"}[1m])) / \n(irate(node_disk_reads_completed{job='cephmetrics',device=~\"[h,s,v]d[a-z]\"}[1m]) + irate(node_disk_writes_completed{job='cephmetrics',device=~\"[h,s,v]d[a-z]\"}[1m]))",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Filesystem Usage - Prometheus Growth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size{mountpoint='/var/lib/cephmetrics/data',fstype='xfs'} - node_filesystem_free{mountpoint='/var/lib/cephmetrics/data',fstype='xfs'}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_filesystem_size{mountpoint='/var/lib/cephmetrics/data',fstype='xfs'}",
     "legendFormat": "Size"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Network Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(\n  irate(node_network_receive_bytes{job='cephmetrics'}[1m]) \n  ) by(instance)",
     "legendFormat": "Network RX"
    },
    {
     "expr": "sum(\n  irate(node_network_transmit_bytes{job='cephmetrics'}[1m]) \n  ) by(instance)",
     "legendFormat": "Network TX"
    }
   ]
  },
  {
   "title": "Filesystem Usage - '/'",
   "type": "graph",
   "description": "Shows data growth on '/' which includes the prometheus data. Prometheus installed 04/14, migrated to separate logical volume 04/22",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size{mountpoint='/',fstype='xfs'} - node_filesystem_free{mountpoint='/',fstype='xfs'}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_filesystem_size{mountpoint='/',fstype='xfs'}",
     "legendFormat": "Size"
    }
   ]
  }
 ]
}