{
 "title": "Ceph RGW Workload",
 "tags": [ "overview" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "rgw_servers",
    "query": "label_values(ceph_rgw_req, ceph_daemon)"
   }
  ]
 },
 "panels": [
  { "title": "RGW Overview - All Gateways", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Requests/sec by RGW Instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by(ceph_daemon) (rate(ceph_rgw_req[30s]))",
     "legendFormat": "{{ceph_daemon}}"
    }
   ]
  },
  {
   "title": "Bandwidth Consumed by Type",
   "type": "graph",
   "description": "Total bytes transferred in/out of all radosgw instances within the cluster",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "sum(rate(ceph_rgw_get_b[30s]))", "legendFormat": "GETs" },
    { "expr": "sum(rate(ceph_rgw_put_b[30s]))", "legendFormat": "PUTs" }
   ]
  },
  {
   "title": "Bandwidth by RGW Instance",
   "type": "graph",
   "description": "Total bytes transferred in/out through get/put operations, by radosgw instance",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(ceph_daemon) \n  (rate(ceph_rgw_get_b[30s]) + rate(ceph_rgw_put_b[30s]))",
     "legendFormat": "{{ceph_daemon}}"
    }
   ]
  },
  {
   "title": "Request Queue Length",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(ceph_rgw_qlen)" }
   ]
  },
  {
   "title": "Failed HTTP Requests",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(ceph_rgw_failed_req)" }
   ]
  },
  {
   "title": "RGW Host Detail : $rgw_servers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "repeat": "rgw_servers",
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Request Breakdown",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(ceph_rgw_failed_req{ceph_daemon=~\"[[rgw_servers]]\"}[30s])",
       "legendFormat": "Requests Failed"
      },
      {
       "expr": "rate(ceph_rgw_get{ceph_daemon=~\"[[rgw_servers]]\"}[30s])",
       "legendFormat": "GETs"
      },
      {
       "expr": "rate(ceph_rgw_put{ceph_daemon=~\"[[rgw_servers]]\"}[30s])",
       "legendFormat": "PUTs"
      },
      {
       "expr": "rate(ceph_rgw_req{ceph_daemon=~\"[[rgw_servers]]\"}[30s]) -\n  (rate(ceph_rgw_get{ceph_daemon=~\"[[rgw_servers]]\"}[30s]) +\n   rate(ceph_rgw_put{ceph_daemon=~\"[[rgw_servers]]\"}[30s]))",
       "legendFormat": "Other"
      }
     ]
    },
    {
     "title": "Bandwidth by HTTP Operation",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 9, "y": 9 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(ceph_rgw_get_b{ceph_daemon=~\"[[rgw_servers]]\"}[30s])",
       "legendFormat": "GETs"
      },
      {
       "expr": "rate(ceph_rgw_put_b{ceph_daemon=~\"[[rgw_servers]]\"}[30s])",
       "legendFormat": "PUTs"
      }
     ]
    },
    {
     "title": "Workload Breakdown",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 9 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "rate(ceph_rgw_failed_req{ceph_daemon=~\"[[rgw_servers]]\"}[30s])",
       "legendFormat": "Failures"
      },
      {
       "expr": "rate(ceph_rgw_get{ceph_daemon=~\"[[rgw_servers]]\"}[30s])",
       "legendFormat": "GETs"
      },
      {
       "expr": "rate(ceph_rgw_put{ceph_daemon=~\"[[rgw_servers]]\"}[30s])",
       "legendFormat": "PUTs"
      },
      {
       "expr": "rate(ceph_rgw_req{ceph_daemon=~\"[[rgw_servers]]\"}[30s]) -\n  (rate(ceph_rgw_get{ceph_daemon=~\"[[rgw_servers]]\"}[30s]) +\n   rate(ceph_rgw_put{ceph_daemon=~\"[[rgw_servers]]\"}[30s]))",
       "legendFormat": "Other (DELETE,LIST)"
      }
     ]
    }
   ]
  }
 ]
}