{
 "title": "iSCSI Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "gateway_iqn",
    "query": "label_values(ceph_iscsi_gateway_tpg_total, gw_iqn)"
   },
   { "name": "interfaces", "query": "(eth|bon|en|ib|mlx)" },
   {
    "name": "iscsi_gws",
    "query": "label_values(ceph_iscsi_scrape_duration_seconds, gw_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "iSCSI Gateway Group : $gateway_iqn",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  { "type": "text", "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 } },
  {
   "title": "Gateways",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(ceph_iscsi_gateway_tpg_total)"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(count by(instance) (ceph_iscsi_client_login))"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(sum(ceph_iscsi_client_login) by(gw_name))"
    }
   ]
  },
  {
   "title": "Defined Capacity",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(sum(ceph_iscsi_lun_size_bytes) by(gw_name))"
    }
   ]
  },
  {
   "title": "LUNs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(count by(instance) (ceph_iscsi_lun_mapped))"
    }
   ]
  },
  {
   "title": "Unused LUNs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(count by(instance) (ceph_iscsi_lun_mapped)) - max(count by(instance) (ceph_iscsi_lun_mapped == 1))"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 } },
  { "type": "text", "gridPos": { "h": 4, "w": 2, "x": 0, "y": 5 } },
  {
   "title": "IOPS",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 2, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum(rate(ceph_iscsi_lun_iops[30s])) by(gw_name))"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 5 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum((sum(rate(ceph_iscsi_lun_read_bytes[30s])) by(gw_name)) + (sum(rate(ceph_iscsi_lun_write_bytes[30s])) by(gw_name)))"
    }
   ]
  },
  {
   "title": "Network Load by Gateway",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 10, "y": 5 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "label_replace(\n  (sum(\n      rate(\n           node_network_transmit_bytes{job=\"node\", instance=~\"($iscsi_gws).*\"}[30s])\n     ) by(instance)),\n     \"gw_name\", \"$1\",\"instance\",\"([^.]*).*\")",
     "legendFormat": "{{gw_name}}"
    }
   ]
  },
  {
   "title": "Active LUN Paths by Gateway",
   "type": "grafana-piechart-panel",
   "description": "LUNs are configured with a primary path (active), and a number of secondary paths (passive).  Under normal circumstances, only the active/primary path is used for I/O. This chart shows the distribution of the active paths across each of the gateways.",
   "gridPos": { "h": 5, "w": 6, "x": 16, "y": 5 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(count(ceph_iscsi_lun_mapped) by(instance,gw_owner)) by(gw_owner)",
     "legendFormat": "{{gw_owner}}"
    }
   ]
  },
  {
   "title": "Gateway Load",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "IOPS by Gateway",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "round(\n  sum by(gw_name) \n    (rate(ceph_iscsi_lun_iops[30s])\n  )\n)",
       "legendFormat": "{{gw_name}}"
      }
     ]
    },
    {
     "title": "Throughput by Gateway",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "round(\n  sum by(gw_name) \n    ((rate(ceph_iscsi_lun_read_bytes[30s])) + \n    (rate(ceph_iscsi_lun_write_bytes[30s]))\n    )\n  )",
       "legendFormat": "{{gw_name}}"
      }
     ]
    },
    {
     "title": "CPU Busy %",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "100 - (avg by (gw) \n        (label_replace(\n          irate(node_cpu{job=\"node\",instance=~\"($iscsi_gws).*\",mode=\"idle\"}[30s]),\n         \"gw\",\"$1\",\"instance\",\"([^.]*).*\")\n        ) * 100)",
       "legendFormat": "{{gw}}"
      }
     ]
    },
    {
     "title": "RAM Util%",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "label_replace(\n  ((node_memory_MemTotal{job=\"node\", instance=~\"($iscsi_gws).*\"} - node_memory_MemFree) / node_memory_MemTotal) * 100, \n  \"gw\", \"$1\", \"instance\",\"([^.]*).*\")",
       "legendFormat": "{{gw}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Client Workloads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "IOPS by Client (R+W)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "round(sum by(shortname) (label_replace(rate(ceph_iscsi_lun_iops[30s]),\"shortname\",\"$2\",\"client_iqn\",\"(.*):(.*)\")))",
       "legendFormat": "{{shortname}}"
      }
     ]
    },
    {
     "title": "Throughput by Client",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "round(\n  sum by(shortname) \n    ((label_replace(rate(ceph_iscsi_lun_read_bytes[30s]),\"shortname\",\"$2\",\"client_iqn\",\"(.*):(.*)\")) +\n     (label_replace(rate(ceph_iscsi_lun_write_bytes[30s]),\"shortname\",\"$2\",\"client_iqn\",\"(.*):(.*)\"))\n    ))",
       "legendFormat": "{{shortname}}"
      }
     ]
    }
   ]
  }
 ]
}