{
 "title": "Network Usage by Server",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "osd_servers",
    "query": "label_values(ceph_disk_occupation, instance)"
   },
   {
    "name": "only_osds",
    "query": "label_values(ceph_server_metadata{services=\"osd\"}, hostname)"
   },
   {
    "name": "mon_servers",
    "query": "label_values(ceph_mon_quorum_status, ceph_daemon)"
   },
   { "name": "interfaces", "query": "(eth|en|bond|mlx|ib)" }
  ]
 },
 "panels": [
  { "title": "Aggregated Network Load", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster Network Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (irate(node_network_receive_bytes{instance=~\"[[mon_servers]].*\",device=~\"[[interfaces]].*\"}[30s])) + \nsum (irate(node_network_transmit_bytes{instance=~\"[[mon_servers]].*\",device=~\"[[interfaces]].*\"}[30s]))",
     "legendFormat": "MONs"
    },
    {
     "expr": "sum (irate(node_network_receive_bytes{instance=~\"[[osd_servers]].*\",device=~\"[[interfaces]].*\"}[30s])) + \nsum (irate(node_network_transmit_bytes{instance=~\"[[osd_servers]].*\",device=~\"[[interfaces]].*\"}[30s]))",
     "legendFormat": "OSDs"
    }
   ]
  },
  {
   "title": "MON Hosts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "MON Network Load",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (irate(node_network_receive_bytes{instance=~\"[[mon_servers]].*\", device=~\"[[interfaces]].*\"}[30s])) by (instance) + \nsum (irate(node_network_transmit_bytes{instance=~\"[[mon_servers]].*\", device=~\"[[interfaces]].*\"}[30s])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "OSD Hosts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "OSD Hosts Network Load",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum \n  (irate(node_network_receive_bytes{instance=~\"[[osd_servers]]\", device=~\"[[interfaces]].*\"}[30s]) + \n  irate(node_network_transmit_bytes{instance=~\"[[osd_servers]]\", device=~\"[[interfaces]].*\"}[30s])) by(instance)\n",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}