{
 "title": "OSD Node Detail",
 "tags": [ "overview" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "osd_servers",
    "label": "OSD Host Name",
    "query": "label_values(ceph_disk_occupation, instance)"
   },
   { "name": "device_id", "label": "Disk Name", "query": "ceph_disk_occupation" },
   { "name": "max_devices", "query": "60" }
  ]
 },
 "panels": [
  { "title": "'$osd_servers' OSD Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "OSDs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ceph_disk_occupation{device=~\"($device_id)\", instance=~\"($osd_servers).*\"})"
    }
   ]
  },
  {
   "title": "Host OSD Breakdown",
   "type": "table",
   "gridPos": { "h": 8, "w": 13, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "(label_replace(ceph_disk_occupation{instance=~\"($osd_servers).*\",device=~\"($device_id)\"},\"aa_hostname\",\"$1\",\"instance\",\"(.*)\") * \n  on(ceph_daemon) group_left(aa_instance) ceph_osd_stat_bytes) *\n  on(ceph_daemon) group_left(device_class,ceph_ver) label_replace(label_replace(ceph_osd_metadata,\"ceph_daemon\",\"osd.$1\",\"id\",\"(.*)\"),\"ceph_ver\",\"$1\",\"ceph_version\",\"ceph version (.*) (.*) (.*) (.*)\")"
    }
   ]
  },
  {
   "title": "Raw Capacity",
   "type": "singlestat",
   "description": "Each OSD consists of a Journal/WAL partition and a data partition. The RAW Capacity shown is the sum of the data partitions across all OSDs on the selected OSD hosts.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ceph_osd_stat_bytes and on (ceph_daemon) ceph_disk_occupation{device=~\"($device_id)\", instance=~\"($osd_servers).*\"})"
    }
   ]
  },
  {
   "title": "'$osd_servers' Performance Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "$osd_servers Disk utilisation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "%Util" }
   ],
   "targets": [
    {
     "expr": "max by (device) (\n  irate(node_disk_io_time_ms[5m]) and on (instance, device) ceph_disk_occupation{instance=~\"($osd_servers).*\", device=~\"($device_id)\"}\n) / 10",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "$osd_servers Disk IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "IOPS" }
   ],
   "targets": [
    {
     "expr": "max by (instance, device) (\n  irate(node_disk_reads_completed{device=~\"($device_id)\", instance=~\"($osd_servers).*\"}[5m]) +\n  irate(node_disk_writes_completed{device=~\"($device_id)\", instance=~\"($osd_servers).*\"}[5m])\n) + on (instance, device) group_left (ceph_daemon) ceph_disk_occupation",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "$osd_servers Disk Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "max by (device) (\n  irate(node_disk_write_time_ms{device=~ \"($device_id)\", instance=~\"($osd_servers).*\"}[5m])\n  /\n  clamp_min(irate(node_disk_writes_completed{device=~ \"($device_id)\", instance=~\"($osd_servers).*\"}[5m]), 0.001)\n+\n  irate(node_disk_read_time_ms{device=~ \"($device_id)\", instance=~\"($osd_servers).*\"}[5m])\n  /\n  clamp_min(irate(node_disk_reads_completed{device=~ \"($device_id)\", instance=~\"($osd_servers).*\"}[5m]), 0.001)\n)",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "$osd_servers Throughput by Disk",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "max by (device) (\n  irate(node_disk_bytes_read{device=~\"($device_id)\", instance=~\"($osd_servers).*\"}[5m]) + \n  irate(node_disk_bytes_written{device=~\"($device_id)\", instance=~\"($osd_servers).*\"}[5m])\n)",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "$osd_servers CPU Utilisation",
   "type": "graph",
   "description": "Shows the CPU breakdown. When multiple servers are selected, only the first host's cpu data is shown",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (mode) (\n  irate(node_cpu{instance=~\"($osd_servers).*\", mode=~\"(irq|nice|softirq|steal|system|user|iowait)\"}[5m])\n) / scalar(\n  sum(irate(node_cpu{instance=~\"($osd_servers).*\"}[5m]))\n) * 100",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal{instance=~\"[[osd_servers]].*\"}) - (\n  sum(node_memory_MemFree{instance=~\"[[osd_servers]].*\"})  + \n  sum(node_memory_Cached{instance=~\"[[osd_servers]].*\"}) + \n  sum(node_memory_Buffers{instance=~\"[[osd_servers]].*\"}) +\n  sum(node_memory_Slab{instance=~\"[[osd_servers]].*\"})\n  )\n  \n",
     "legendFormat": "used"
    },
    {
     "expr": "sum(node_memory_MemFree{instance=~\"[[osd_servers]].*\"}) ",
     "legendFormat": "Free"
    },
    {
     "expr": "sum(node_memory_Cached{instance=~\"[[osd_servers]].*\"}) + \nsum(node_memory_Buffers{instance=~\"[[osd_servers]].*\"}) +\nsum(node_memory_Slab{instance=~\"[[osd_servers]].*\"}) \n",
     "legendFormat": "buffers/cache"
    },
    {
     "expr": "sum(node_memory_MemTotal{instance=~\"[[osd_servers]].*\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "$osd_servers Network Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (device) (irate(node_network_receive_bytes{instance=~\"($osd_servers).*\", device=~\"(eth|en|bond|ib|mlx|p).*\"}[5m]))",
     "legendFormat": "{{device}}.rx"
    },
    {
     "expr": "sum by (device) (irate(node_network_transmit_bytes{instance=~\"($osd_servers).*\", device=~\"(eth|en|bond|ib|mlx|p).*\"}[5m]))",
     "legendFormat": "{{device}}.tx"
    }
   ]
  }
 ]
}