{
 "title": "Host Details",
 "tags": [ "overview" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "ceph_hosts",
    "label": "Hostname",
    "query": "label_values(node_cpu, instance) "
   }
  ]
 },
 "panels": [
  { "title": "$ceph_hosts System Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "OSDs",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ceph_disk_occupation{instance=~\"($ceph_hosts).*\"})"
    }
   ]
  },
  {
   "title": "CPU Utilisation",
   "type": "graph",
   "description": "Shows the CPU breakdown. When multiple servers are selected, only the first host's cpu data is shown",
   "gridPos": { "h": 10, "w": 6, "x": 3, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (mode) (\n  irate(node_cpu{instance=~\"($ceph_hosts).*\", mode=~\"(irq|nice|softirq|steal|system|user|iowait)\"}[5m])\n) / scalar(\n  sum(irate(node_cpu{instance=~\"($ceph_hosts).*\"}[5m]))\n) * 100",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 9, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal{instance=~\"[[ceph_hosts]].*\"} - (\n  node_memory_MemFree{instance=~\"[[ceph_hosts]].*\"}  + \n  node_memory_Cached{instance=~\"[[ceph_hosts]].*\"} + \n  node_memory_Buffers{instance=~\"[[ceph_hosts]].*\"} +\n  node_memory_Slab{instance=~\"[[ceph_hosts]].*\"}\n  )\n  \n",
     "legendFormat": "used"
    },
    {
     "expr": "node_memory_MemFree{instance=~\"[[ceph_hosts]].*\"} ",
     "legendFormat": "Free"
    },
    {
     "expr": "node_memory_Cached{instance=~\"[[ceph_hosts]].*\"} + \nnode_memory_Buffers{instance=~\"[[ceph_hosts]].*\"} +\nnode_memory_Slab{instance=~\"[[ceph_hosts]].*\"} \n",
     "legendFormat": "buffers/cache"
    },
    {
     "expr": "node_memory_MemTotal{instance=~\"[[ceph_hosts]].*\"}",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Network Load",
   "type": "graph",
   "description": "Show the network load (rx,tx) across all interfaces (excluding loopback 'lo')",
   "gridPos": { "h": 10, "w": 6, "x": 15, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (device) (irate(node_network_receive_bytes{instance=~\"($ceph_hosts).*\",device!=\"lo\"}[5m]))",
     "legendFormat": "{{device}}.rx"
    },
    {
     "expr": "sum by (device) (irate(node_network_transmit_bytes{instance=~\"($ceph_hosts).*\",device!=\"lo\"}[5m]))",
     "legendFormat": "{{device}}.tx"
    }
   ]
  },
  {
   "title": "Network Drops (last 15mins)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_drop{instance=~\"[[ceph_hosts]].*\"}[1m]) + \nirate(node_network_receive_drop{instance=~\"[[ceph_hosts]].*\"}[1m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Raw Capacity",
   "type": "singlestat",
   "description": "Each OSD consists of a Journal/WAL partition and a data partition. The RAW Capacity shown is the sum of the data partitions across all OSDs on the selected OSD hosts.",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ceph_osd_stat_bytes and on (ceph_daemon) ceph_disk_occupation{instance=~\"($ceph_hosts).*\"})"
    }
   ]
  },
  {
   "title": "Network Errors(last 15mins)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_errs{instance=~\"[[ceph_hosts]].*\"}[1m]) + \nirate(node_network_receive_errs{instance=~\"[[ceph_hosts]].*\"}[1m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "OSD Disk Performance Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "$ceph_hosts Disk IOPS",
     "type": "graph",
     "description": "For any OSD devices on the host, this chart shows the iops per physical device. Each device is shown by it's name and corresponding OSD id value",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short", "label": "IOPS" }
     ],
     "targets": [
      {
       "expr": "(\n  ((irate(node_disk_reads_completed{instance=~\"($ceph_hosts).*\"}[5m]) + (irate(node_disk_writes_completed{instance=~\"($ceph_hosts).*\"}[5m])))\n  * on(instance, device) group_left(osd_id) label_replace(ceph_disk_occupation, \"osd_id\",\"$1\",\"ceph_daemon\",\"osd.(.*)\")) \n)",
       "legendFormat": "{{device}}({{osd_id}})"
      }
     ]
    },
    {
     "title": "$ceph_hosts Disk utilisation",
     "type": "graph",
     "description": "Show disk utilization % (util) of any OSD devices on the host by the physical device name and associated OSD id.",
     "gridPos": { "h": 9, "w": 11, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short", "label": "%Util" }
     ],
     "targets": [
      {
       "expr": "(\n  irate(node_disk_io_time_ms[5m]) * on(instance, device) group_left(osd_id) label_replace(ceph_disk_occupation{instance=~\"($ceph_hosts).*\"}, \"osd_id\",\"$1\",\"ceph_daemon\",\"osd.(.*)\")\n) / 10",
       "legendFormat": "{{device}}({{osd_id}})"
      }
     ]
    },
    {
     "title": "$ceph_hosts Disk Latency",
     "type": "graph",
     "description": "For OSD hosts, this chart shows the latency at the physical drive. Each drive is shown by device name, with it's corresponding OSD id",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "max by(instance,device) (\n  (irate(node_disk_write_time_ms{ instance=~\"($ceph_hosts).*\"}[5m]) )\n  /\n  clamp_min(irate(node_disk_writes_completed{ instance=~\"($ceph_hosts).*\"}[5m]), 0.001) or \n  (irate(node_disk_read_time_ms{ instance=~\"($ceph_hosts).*\"}[5m]) )\n  /\n  clamp_min(irate(node_disk_reads_completed{ instance=~\"($ceph_hosts).*\"}[5m]), 0.001)\n  ) * on(instance,device) group_left(osd_id) label_replace(ceph_disk_occupation,\"osd_id\",\"$1\",\"ceph_daemon\",\"osd.(.*)\")",
       "legendFormat": "{{device}}({{osd_id}})"
      }
     ]
    },
    {
     "title": "$ceph_hosts Throughput by Disk",
     "type": "graph",
     "description": "For OSD hosts, this chart shows the disk bandwidth (read bytes/sec + write bytes/sec) of the physical OSD device. Each device is shown by device name, and corresponding OSD id",
     "gridPos": { "h": 9, "w": 11, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": " (irate(node_disk_bytes_read{instance=~\"($ceph_hosts).*\"}[5m])  + \n  irate(node_disk_bytes_written{instance=~\"($ceph_hosts).*\"}[5m])) * on(instance,device) group_left(osd_id) label_replace(ceph_disk_occupation,\"osd_id\",\"$1\",\"ceph_daemon\",\"osd.(.*)\")",
       "legendFormat": "{{device}}({{osd_id}})"
      }
     ]
    }
   ]
  }
 ]
}