{
 "title": "iSCSI Client Details",
 "tags": [ "iscsi" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "client_iqn",
    "label": "Client IQN",
    "query": "label_values(ceph_iscsi_client_login,client_iqn)"
   },
   {
    "name": "gateway_iqn",
    "query": "label_values(ceph_iscsi_gateway_tpg_total, gw_iqn)"
   },
   { "name": "interfaces", "query": "(eth|bon|en|ib|mlx)" }
  ]
 },
 "panels": [
  { "title": "Client Details for $client_iqn", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "IOPS Detail for $client_iqn",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "round(sum by(lun_name) (irate(ceph_iscsi_lun_iops{client_iqn=~\"[[client_iqn]]\"}[30s])))",
     "legendFormat": "{{lun_name}}"
    }
   ]
  },
  {
   "title": "Throughput for $client_iqn",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "round(sum by(lun_name) (irate(ceph_iscsi_lun_read_bytes{client_iqn=~\"[[client_iqn]]\"}[30s])))",
     "legendFormat": "{{lun_name}}(r)"
    },
    {
     "expr": "round(sum by(lun_name) (irate(ceph_iscsi_lun_write_bytes{client_iqn=~\"[[client_iqn]]\"}[30s])))",
     "legendFormat": "{{lun_name}}(w)"
    }
   ]
  },
  {
   "title": "LUN Details for $client_iqn",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "max(label_replace(ceph_iscsi_client_lun{client_iqn=~\"[[client_iqn]]\"},\"a_lun_name\",\"$1\", \"lun_name\",\"(.*)\")) \n  by(a_lun_name,client_iqn) +\non(a_lun_name)  group_right(client_iqn) \n  max(label_replace(ceph_iscsi_lun_mapped,\"a_lun_name\",\"$1\",\"lun_name\",\"(.*)\")) by(a_lun_name, gw_owner) +\non(a_lun_name) group_right(client_iqn, gw_owner) \n  max(label_replace(ceph_iscsi_lun_size_bytes,\"a_lun_name\",\"$1\",\"lun_name\",\"(.*)\")) by(a_lun_name)\n\n"
    }
   ]
  }
 ]
}