{
 "title": "Ceph Backend Storage",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "percentile", "label": "Percentile", "query": "80,85,90,95,98" },
   { "name": "osd_servers", "label": "OSD Hostname", "query": "ceph_disk_occupation" },
   { "name": "disk_full_threshold", "query": "85" }
  ]
 },
 "panels": [
  { "title": "Disk/OSD Host Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "OSDs down",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "count(ceph_osd_up < 0.5)" }
   ]
  },
  {
   "title": "Disks Near Full",
   "type": "table",
   "gridPos": { "h": 7, "w": 4, "x": 2, "y": 1 },
   "targets": [
    {
     "expr": "ceph_osd_stat_bytes_used / ceph_osd_stat_bytes * 100 > $disk_full_threshold",
     "legendFormat": "{{ceph_daemon}}"
    }
   ]
  },
  {
   "title": "OSD Host Capacity Summary",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "sum by (instance) (\n  ceph_disk_occupation{instance=~\"($osd_servers)\"}*0 + on (ceph_daemon) group_right(instance) ceph_osd_stat_bytes\n)"
    },
    {
     "expr": "count by (instance) (\n  ceph_disk_occupation{instance=~\"($osd_servers)\"}\n)"
    }
   ]
  },
  {
   "title": "Disk/OSD Load Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Drive Utilization Heatmap - $osd_servers",
     "type": "heatmap",
     "description": "The heatmap categorizes disk utilization into discrete buckets (e.g util 0-5) and shows the frequency of the number of disks that fall within that range as a color. The color chosen depends on the number of disks in the 'bucket', ranging from green (low) to red (high). Hover over a colored block to show the number of disks at a given util% for that time interval (20secs).",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "irate(node_disk_io_time_ms{instance=~\"[[osd_servers]]\"}[1m]) / 10 and on (instance, device) ceph_disk_occupation"
      }
     ]
    },
    {
     "title": "Disk Throughput - $osd_servers",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(\n  irate(node_disk_bytes_read{instance=~\"($osd_servers)\"}[5m]) and on (instance, device) ceph_disk_occupation\n)",
       "legendFormat": "Read throughtput"
      },
      {
       "expr": "sum(\n  irate(node_disk_bytes_written{instance=~\"($osd_servers)\"}[5m]) and on (instance, device) ceph_disk_occupation\n)",
       "legendFormat": "Write throughtput"
      }
     ]
    },
    {
     "title": "Disk Latency - $osd_servers OSDs @ $percentile%ile",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "quantile($percentile/100.0, (\n  irate(node_disk_read_time_ms[5m]) / clamp_min(irate(node_disk_reads_completed[5m]), 0.001)\n  and on (instance, device) ceph_disk_occupation{instance=~\"($osd_servers)\"}\n))",
       "legendFormat": "Read latency"
      },
      {
       "expr": "quantile($percentile/100.0, (\n  irate(node_disk_write_time_ms[5m]) / clamp_min(irate(node_disk_writes_completed[5m]), 0.001)\n  and on (instance, device) ceph_disk_occupation{instance=~\"($osd_servers)\"}\n))",
       "legendFormat": "Write latency"
      }
     ]
    },
    {
     "title": "Disk Utilization - $osd_servers OSDs at $percentile%ile",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "quantile($percentile/100, (\n  max by (device) (\n    irate(node_disk_io_time_ms[5m]) and on (instance, device) ceph_disk_occupation{instance=~\"($osd_servers)\"}\n  ) / 10\n))",
       "legendFormat": "disk busy %"
      }
     ]
    },
    {
     "title": "IOPS per Disk @ $percentile%ile - $osd_servers OSDs",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "quantile($percentile/100.0, (\n  avg by (device) (\n    irate(node_disk_reads_completed[5m]) and on (instance, device) ceph_disk_occupation{instance=~\"($osd_servers)\"}\n  ) +\n  avg by (device) (\n    irate(node_disk_writes_completed[5m]) and on (instance, device) ceph_disk_occupation{instance=~\"($osd_servers)\"}\n  )\n))",
       "legendFormat": "IOPS/spindle"
      }
     ]
    },
    {
     "title": "Total Disk IOPS - $osd_servers OSDs",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "quantile($percentile/100.0, (\n  sum(\n    irate(node_disk_reads_completed[5m]) and on (instance, device) ceph_disk_occupation{instance=~\"($osd_servers)\"}\n  ) +\n  sum(\n    irate(node_disk_writes_completed[5m]) and on (instance, device) ceph_disk_occupation{instance=~\"($osd_servers)\"}\n  )\n))"
      }
     ]
    }
   ]
  },
  {
   "title": "OSD Host CPU and Network Load",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Utilization - $osd_servers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "quantile($percentile / 100.0, (\n  sum by (instance) (\n    irate(node_cpu{mode=~\"(irq|nice|system|user)\"}[5m])\n  ) / sum by (instance) (\n    irate(node_cpu[5m])\n  )\n) * 100)",
       "legendFormat": "Cluster-wide CPU Busy @ $percentile%ile"
      },
      {
       "expr": "avg(\n  sum by (instance) (\n    irate(node_cpu{instance=~\"($osd_servers)\", mode=~\"(irq|nice|system|user)\"}[5m])\n  ) / sum by (instance) (\n    irate(node_cpu{instance=~\"($osd_servers)\"}[5m])\n  )\n) * 100",
       "legendFormat": "Average OSD Host(s) CPU Busy"
      }
     ]
    },
    {
     "title": "Network Load - $osd_servers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (irate(node_network_receive_bytes{instance=~\"($osd_servers)\", device=~\"(eth|en|bond|ib|mlx).*\"}[5m])) + \nsum (irate(node_network_transmit_bytes{instance=~\"($osd_servers)\", device=~\"(eth|en|bond|ib|mlx).*\"}[5m]))",
       "legendFormat": "Network load (rx+tx)"
      }
     ]
    }
   ]
  }
 ]
}