{
 "title": "MDS Performance",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "mds_servers",
    "label": "MDS Server",
    "query": "label_values(ceph_mds_inodes, ceph_daemon)"
   }
  ]
 },
 "panels": [
  { "title": "MDS Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active MDS Servers",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "count(ceph_mds_metadata)" }
   ]
  },
  {
   "title": "Filesystems",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "count(ceph_fs_metadata)" }
   ]
  },
  {
   "title": "Clients",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ceph_mds_sessions_session_count)"
    }
   ]
  },
  { "title": "MDS Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "MDS Workload - $mds_servers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(ceph_objecter_op_r{ceph_daemon=~\"($mds_servers).*\"})",
     "legendFormat": "MDS Reads"
    },
    {
     "expr": "sum(ceph_objecter_op_w{ceph_daemon=~\"($mds_servers).*\"})",
     "legendFormat": "MDS Writes"
    }
   ]
  },
  {
   "title": "Client Request Load - $mds_servers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "ceph_mds_server_handle_client_request{ceph_daemon=~\"($mds_servers).*\"}",
     "legendFormat": "{{ceph_daemon}}"
    }
   ]
  }
 ]
}